'use client';

import { useMemo, useState, type ReactNode } from 'react';
import Calendar from 'react-calendar';
import 'react-calendar/dist/Calendar.css';
import {
  ArrowDownRight,
  ArrowRightLeft,
  ArrowUpRight,
  Book,
  Calendar as CalendarIcon,
  Download,
  Edit3,
  Plus,
  Tag,
  Trash2,
  Wallet,
  X,
} from 'lucide-react';
import { useNotifications } from '../components/NotificationContext';
import { useLedger, useSettings } from '../components/FinanceContext';
import { Transaction, SemanticTransactionType } from '@/lib/types';
import { exportTransactionsToCSV } from '../../lib/utils/export';
import { formatDate } from '@/lib/utils/format';
import { MoneyValue } from '@/app/components/ui/MoneyValue';
import { InfoHint } from '@/app/components/ui/InfoHint';
import { PageSkeleton, PageState } from '@/app/components/ui/PageState';
import {
  getTransactionSemanticLabel,
  isAutoGeneratedTransaction,
  isTransferTransaction,
} from '@/lib/utils/transactions';

const FILTERS: Array<{ id: 'ALL' | SemanticTransactionType; label: string }> = [
  { id: 'ALL', label: 'All' },
  { id: 'INCOME', label: 'Income' },
  { id: 'EXPENSE', label: 'Expense' },
  { id: 'TRANSFER', label: 'Transfer' },
  { id: 'INVESTMENT_BUY', label: 'Investment Buy' },
  { id: 'INVESTMENT_SELL', label: 'Investment Sell' },
  { id: 'ADJUSTMENT', label: 'Adjustment' },
];

export default function LedgerClient() {
  const {
    transactions,
    accounts,
    addTransaction,
    updateTransaction,
    deleteTransaction,
    loading,
    error,
    lastUpdatedAt,
  } = useLedger();
  const { settings } = useSettings();
  const { showNotification, showActionNotification } = useNotifications();

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editId, setEditId] = useState<number | null>(null);
  const [pendingDeleteIds, setPendingDeleteIds] = useState<number[]>([]);
  const [selectedDate, setSelectedDate] = useState<Date | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterCategory, setFilterCategory] = useState('All');
  const [filterAccount, setFilterAccount] = useState<number | 'All'>('All');
  const [filterType, setFilterType] = useState<'ALL' | SemanticTransactionType>('ALL');

  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('');
  const [amount, setAmount] = useState('');
  const [transactionType, setTransactionType] = useState<SemanticTransactionType>('EXPENSE');
  const [accountId, setAccountId] = useState('');
  const [targetAccountId, setTargetAccountId] = useState('');

  const visibleTransactions = useMemo(
    () => transactions.filter((transaction) => !pendingDeleteIds.includes(transaction.id)),
    [pendingDeleteIds, transactions]
  );

  const categories = useMemo(
    () => [
      'All',
      ...new Set(visibleTransactions.map((transaction) => String(transaction.category))),
    ],
    [visibleTransactions]
  );

  const filteredTransactions = useMemo(
    () =>
      visibleTransactions.filter((transaction) => {
        const matchesSearch =
          transaction.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
          String(transaction.category).toLowerCase().includes(searchQuery.toLowerCase());
        const matchesCategory =
          filterCategory === 'All' || String(transaction.category) === filterCategory;
        const matchesAccount = filterAccount === 'All' || transaction.accountId === filterAccount;
        const matchesType = filterType === 'ALL' || transaction.transactionType === filterType;
        const matchesDate =
          !selectedDate || transaction.date === selectedDate.toISOString().split('T')[0];
        return matchesSearch && matchesCategory && matchesAccount && matchesType && matchesDate;
      }),
    [filterAccount, filterCategory, filterType, searchQuery, selectedDate, visibleTransactions]
  );

  const groupedTransactions = useMemo(() => {
    const groups: Record<string, Transaction[]> = {};
    filteredTransactions.forEach((transaction) => {
      if (!groups[transaction.date]) groups[transaction.date] = [];
      groups[transaction.date].push(transaction);
    });
    return Object.entries(groups).sort((a, b) => b[0].localeCompare(a[0]));
  }, [filteredTransactions]);

  const stats = useMemo(() => {
    const income = filteredTransactions
      .filter((transaction) => transaction.transactionType === 'INCOME')
      .reduce((sum, transaction) => sum + transaction.amount, 0);
    const expenses = filteredTransactions
      .filter((transaction) => transaction.transactionType === 'EXPENSE')
      .reduce((sum, transaction) => sum + transaction.amount, 0);
    const transfers = filteredTransactions
      .filter((transaction) => isTransferTransaction(transaction))
      .reduce((sum, transaction) => sum + transaction.amount, 0);
    return { income, expenses, transfers, netMovement: income - expenses };
  }, [filteredTransactions]);

  const accountName = (id?: number) => accounts.find((account) => account.id === id)?.name;

  const resetForm = () => {
    setDescription('');
    setCategory('');
    setAmount('');
    setDate(new Date().toISOString().split('T')[0]);
    setTransactionType('EXPENSE');
    setAccountId('');
    setTargetAccountId('');
    setEditId(null);
  };

  const toDirection = (type: SemanticTransactionType): 'Income' | 'Expense' =>
    type === 'INCOME' || type === 'INVESTMENT_SELL' ? 'Income' : 'Expense';

  const saveTransaction = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!description || !amount || !category) return;

    const payload = {
      date,
      description,
      category,
      type: toDirection(transactionType),
      transactionType,
      amount: parseFloat(amount),
      accountId: accountId ? Number(accountId) : undefined,
      metadata:
        transactionType === 'TRANSFER' && targetAccountId
          ? {
              targetAccountId: Number(targetAccountId),
              targetAccountName: accountName(Number(targetAccountId)),
              autoGenerated: false,
              sourceTable: 'transactions',
            }
          : { autoGenerated: false, sourceTable: 'transactions' },
    };

    if (editId) {
      await updateTransaction(editId, payload);
      showNotification('success', 'Ledger entry updated');
    } else {
      await addTransaction(payload);
      showNotification('success', 'Ledger entry saved');
    }

    resetForm();
    setIsModalOpen(false);
  };

  const editTransaction = (transaction: Transaction) => {
    setEditId(transaction.id);
    setDescription(transaction.description);
    setCategory(String(transaction.category));
    setAmount(String(transaction.amount));
    setDate(transaction.date);
    setTransactionType(transaction.transactionType);
    setAccountId(transaction.accountId ? String(transaction.accountId) : '');
    setTargetAccountId(
      transaction.metadata?.targetAccountId ? String(transaction.metadata.targetAccountId) : ''
    );
    setIsModalOpen(true);
  };

  const scheduleDelete = (transaction: Transaction) => {
    setPendingDeleteIds((current) => [...current, transaction.id]);
    showActionNotification({
      type: 'warning',
      message: `${transaction.description} removed. Undo within 8 seconds to restore it.`,
      actionLabel: 'Undo',
      duration: 8000,
      onAction: () => {
        setPendingDeleteIds((current) => current.filter((id) => id !== transaction.id));
        showNotification('info', 'Entry restored');
      },
      onDismiss: async () => {
        await deleteTransaction(transaction.id);
        setPendingDeleteIds((current) => current.filter((id) => id !== transaction.id));
        showNotification('success', 'Entry deleted');
      },
    });
  };

  if (loading) {
    return (
      <div className="page-container">
        <PageSkeleton cardCount={4} rowCount={6} />
      </div>
    );
  }

  if (error) {
    return (
      <div className="page-container">
        <PageState
          variant="error"
          title="Ledger could not be loaded"
          description={error}
          actionLabel="Retry"
          onAction={() => window.location.reload()}
        />
      </div>
    );
  }

  return (
    <div className="page-container" style={{ padding: 'clamp(16px, 4vw, 24px)' }}>
      <div style={{ maxWidth: '1400px', margin: '0 auto' }}>
        <div className="page-header">
          <div>
            <div
              style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}
            >
              <div
                style={{
                  background: 'rgba(106, 166, 255, 0.1)',
                  padding: '10px',
                  borderRadius: '12px',
                  color: '#6aa6ff',
                }}
              >
                <Book size={24} strokeWidth={2.5} />
              </div>
              <h1 className="page-title">Ledger</h1>
            </div>
            <p className="page-subtitle">
              Every movement, classified as income, expense, transfer, or investment activity.
            </p>
            <p style={{ color: '#64748b', fontSize: '0.82rem', marginTop: '8px' }}>
              As of {lastUpdatedAt ? formatDate(lastUpdatedAt) : 'today'}
            </p>
          </div>

          <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
            <button
              onClick={() => {
                exportTransactionsToCSV(visibleTransactions);
                showNotification('success', 'Ledger exported to CSV');
              }}
              className="page-state__button"
            >
              <Download size={16} /> Export
            </button>
            <button
              onClick={() => setIsModalOpen(true)}
              className="header-add-btn"
              style={{ background: 'linear-gradient(135deg, #6aa6ff 0%, #4f7dff 100%)' }}
            >
              <Plus size={20} strokeWidth={3} /> Add Entry
            </button>
          </div>
        </div>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 220px), 1fr))',
            gap: '16px',
            marginBottom: '24px',
          }}
        >
          <LedgerStat
            label={
              <InfoHint
                label="Inflow"
                description="Recognized income only. Investment sells are tracked separately as activity."
              />
            }
            value={<MoneyValue amount={stats.income} compact={settings.compactNumbers} />}
            accent="#2bd576"
          />
          <LedgerStat
            label={
              <InfoHint
                label="Spending"
                description="Consumption expenses only. Investment buys and transfers are excluded."
              />
            }
            value={<MoneyValue amount={stats.expenses} compact={settings.compactNumbers} />}
            accent="#ff4d6d"
          />
          <LedgerStat
            label={
              <InfoHint
                label="Transfers"
                description="Internal movement between accounts or containers. Excluded from net movement."
              />
            }
            value={<MoneyValue amount={stats.transfers} compact={settings.compactNumbers} />}
            accent="#6aa6ff"
          />
          <LedgerStat
            label={
              <InfoHint
                label="Net movement"
                description="Income minus spending, excluding internal transfers so movement is not double-counted."
              />
            }
            value={
              <MoneyValue
                amount={stats.netMovement}
                compact={settings.compactNumbers}
                showSign={stats.netMovement >= 0}
              />
            }
            accent={stats.netMovement >= 0 ? '#2bd576' : '#ff4d6d'}
          />
        </div>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 320px), 1fr))',
            gap: '24px',
          }}
        >
          <div
            className="premium-card"
            style={{ display: 'grid', gap: '16px', alignContent: 'start' }}
          >
            <div>
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px',
                  marginBottom: '16px',
                  color: '#6aa6ff',
                }}
              >
                <CalendarIcon size={14} />
                <span
                  style={{
                    fontWeight: '900',
                    fontSize: '0.72rem',
                    textTransform: 'uppercase',
                    letterSpacing: '1px',
                  }}
                >
                  Date Filter
                </span>
              </div>
              <Calendar
                value={selectedDate}
                onChange={(value) => setSelectedDate(value as Date)}
                className="custom-calendar"
              />
            </div>

            <input
              className="form-input"
              value={searchQuery}
              onChange={(event) => setSearchQuery(event.target.value)}
              placeholder="Search description or category"
            />
            <select
              className="form-input"
              value={filterCategory}
              onChange={(event) => setFilterCategory(event.target.value)}
            >
              {categories.map((entry) => (
                <option key={entry} value={entry}>
                  {entry}
                </option>
              ))}
            </select>
            <select
              className="form-input"
              value={filterAccount}
              onChange={(event) =>
                setFilterAccount(event.target.value === 'All' ? 'All' : Number(event.target.value))
              }
            >
              <option value="All">All accounts</option>
              {accounts.map((account) => (
                <option key={account.id} value={account.id}>
                  {account.name}
                </option>
              ))}
            </select>

            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
              {FILTERS.map((filter) => (
                <button
                  key={filter.id}
                  type="button"
                  onClick={() => setFilterType(filter.id)}
                  style={{
                    minHeight: '36px',
                    padding: '8px 12px',
                    borderRadius: '999px',
                    border: '1px solid rgba(255,255,255,0.08)',
                    background:
                      filterType === filter.id
                        ? 'rgba(106, 166, 255, 0.16)'
                        : 'rgba(255,255,255,0.03)',
                    color: filterType === filter.id ? '#fff' : '#94a3b8',
                    cursor: 'pointer',
                    fontWeight: '700',
                    fontSize: '0.8rem',
                  }}
                >
                  {filter.label}
                </button>
              ))}
            </div>
          </div>

          <div className="premium-card" style={{ display: 'grid', gap: '22px' }}>
            {groupedTransactions.length > 0 ? (
              groupedTransactions.map(([groupDate, group]) => (
                <div key={groupDate}>
                  <div
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '12px',
                      marginBottom: '12px',
                    }}
                  >
                    <div
                      style={{
                        background: '#162232',
                        padding: '6px 12px',
                        borderRadius: '12px',
                        fontWeight: '900',
                      }}
                    >
                      {formatDate(groupDate)}
                    </div>
                    <div
                      style={{
                        height: '1px',
                        flex: 1,
                        background: 'linear-gradient(to right, #223041, transparent)',
                      }}
                    />
                  </div>
                  <div style={{ display: 'grid', gap: '12px' }}>
                    {group.map((transaction) => {
                      const isTransfer = isTransferTransaction(transaction);
                      const accent =
                        transaction.transactionType === 'TRANSFER'
                          ? '#6aa6ff'
                          : transaction.type === 'Income'
                            ? '#2bd576'
                            : '#ff4d6d';
                      const icon = isTransfer ? (
                        <ArrowRightLeft size={18} />
                      ) : transaction.type === 'Income' ? (
                        <ArrowUpRight size={18} />
                      ) : (
                        <ArrowDownRight size={18} />
                      );

                      return (
                        <div
                          key={transaction.id}
                          className="tx-row tx-row--expense"
                          onClick={() => editTransaction(transaction)}
                          style={{ cursor: 'pointer' }}
                        >
                          <div
                            style={{
                              display: 'flex',
                              alignItems: 'center',
                              gap: '14px',
                              flex: 1,
                              minWidth: 0,
                            }}
                          >
                            <div
                              style={{
                                width: '44px',
                                height: '44px',
                                borderRadius: '12px',
                                background: `${accent}20`,
                                color: accent,
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                flexShrink: 0,
                              }}
                            >
                              {icon}
                            </div>
                            <div style={{ minWidth: 0 }}>
                              <div
                                style={{
                                  color: '#fff',
                                  fontWeight: '800',
                                  overflow: 'hidden',
                                  textOverflow: 'ellipsis',
                                  whiteSpace: 'nowrap',
                                }}
                              >
                                {transaction.description}
                              </div>
                              <div
                                style={{
                                  display: 'flex',
                                  alignItems: 'center',
                                  gap: '8px',
                                  flexWrap: 'wrap',
                                  fontSize: '0.78rem',
                                  color: '#94a3b8',
                                }}
                              >
                                <span
                                  style={{
                                    display: 'inline-flex',
                                    alignItems: 'center',
                                    gap: '4px',
                                  }}
                                >
                                  <Tag size={12} />{' '}
                                  {getTransactionSemanticLabel(transaction.transactionType)}
                                </span>
                                <span>{String(transaction.category)}</span>
                                {accountName(transaction.accountId) ? (
                                  <span
                                    style={{
                                      display: 'inline-flex',
                                      alignItems: 'center',
                                      gap: '4px',
                                    }}
                                  >
                                    <Wallet size={12} /> {accountName(transaction.accountId)}
                                  </span>
                                ) : null}
                                {transaction.metadata?.targetAccountName ? (
                                  <span>{transaction.metadata.targetAccountName}</span>
                                ) : null}
                                {isAutoGeneratedTransaction(transaction.metadata) ? (
                                  <span style={{ color: '#f59e0b', fontWeight: '800' }}>
                                    AUTO ENTRY
                                  </span>
                                ) : null}
                              </div>
                            </div>
                          </div>

                          <div
                            style={{
                              display: 'flex',
                              alignItems: 'center',
                              gap: '8px',
                              flexWrap: 'wrap',
                            }}
                          >
                            <div
                              className="table-nums"
                              style={{ fontWeight: '900', color: accent }}
                            >
                              <MoneyValue
                                amount={transaction.amount}
                                compact={settings.compactNumbers}
                                showSign={transaction.type === 'Income'}
                              />
                            </div>
                            <button
                              className="action-btn action-btn--edit"
                              onClick={(event) => {
                                event.stopPropagation();
                                editTransaction(transaction);
                              }}
                              data-label="Edit"
                              aria-label="Edit entry"
                            >
                              <Edit3 size={14} />
                            </button>
                            <button
                              className="action-btn action-btn--delete"
                              onClick={(event) => {
                                event.stopPropagation();
                                scheduleDelete(transaction);
                              }}
                              data-label="Delete"
                              aria-label="Delete entry"
                            >
                              <Trash2 size={14} />
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))
            ) : (
              <PageState
                title="No matching entries"
                description="No records match the current filters. Clear one or more filters to see more activity."
                actionLabel="Reset filters"
                onAction={() => {
                  setSearchQuery('');
                  setFilterCategory('All');
                  setFilterAccount('All');
                  setFilterType('ALL');
                  setSelectedDate(null);
                }}
              />
            )}
          </div>
        </div>
      </div>

      {isModalOpen ? (
        <div className="modal-overlay">
          <div className="modal-card" style={{ maxWidth: '560px' }}>
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: '24px',
              }}
            >
              <h2 style={{ fontSize: 'clamp(1.4rem, 3vw, 1.75rem)', fontWeight: '950', margin: 0 }}>
                {editId ? 'Edit entry' : 'New ledger entry'}
              </h2>
              <button className="modal-close" onClick={() => setIsModalOpen(false)}>
                <X size={24} />
              </button>
            </div>

            <form onSubmit={saveTransaction} style={{ display: 'grid', gap: '20px' }}>
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                {FILTERS.filter((filter) => filter.id !== 'ALL').map((filter) => (
                  <button
                    key={filter.id}
                    type="button"
                    onClick={() => setTransactionType(filter.id as SemanticTransactionType)}
                    style={{
                      minHeight: '38px',
                      padding: '8px 12px',
                      borderRadius: '999px',
                      border: '1px solid rgba(255,255,255,0.08)',
                      background:
                        transactionType === filter.id
                          ? 'rgba(106, 166, 255, 0.16)'
                          : 'rgba(255,255,255,0.03)',
                      color: transactionType === filter.id ? '#fff' : '#94a3b8',
                      cursor: 'pointer',
                      fontWeight: '700',
                    }}
                  >
                    {filter.label}
                  </button>
                ))}
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <input
                  className="form-input"
                  type="date"
                  value={date}
                  onChange={(event) => setDate(event.target.value)}
                />
                <input
                  className="form-input table-nums"
                  type="number"
                  value={amount}
                  onChange={(event) => setAmount(event.target.value)}
                  placeholder="Amount"
                  required
                />
              </div>
              <input
                className="form-input"
                value={description}
                onChange={(event) => setDescription(event.target.value)}
                placeholder="Description"
                required
              />
              <input
                className="form-input"
                value={category}
                onChange={(event) => setCategory(event.target.value)}
                placeholder="Category"
                required
              />

              <div
                style={{
                  display: 'grid',
                  gridTemplateColumns: transactionType === 'TRANSFER' ? '1fr 1fr' : '1fr',
                  gap: '16px',
                }}
              >
                <select
                  className="form-input"
                  value={accountId}
                  onChange={(event) => setAccountId(event.target.value)}
                >
                  <option value="">Primary account</option>
                  {accounts.map((account) => (
                    <option key={account.id} value={account.id}>
                      {account.name}
                    </option>
                  ))}
                </select>

                {transactionType === 'TRANSFER' ? (
                  <select
                    className="form-input"
                    value={targetAccountId}
                    onChange={(event) => setTargetAccountId(event.target.value)}
                    required
                  >
                    <option value="">Destination account</option>
                    {accounts.map((account) => (
                      <option key={account.id} value={account.id}>
                        {account.name}
                      </option>
                    ))}
                  </select>
                ) : null}
              </div>

              <button type="submit" className="btn-primary btn-primary--indigo">
                {editId ? 'Save changes' : 'Save entry'}
              </button>
            </form>
          </div>
        </div>
      ) : null}
    </div>
  );
}

function LedgerStat({
  label,
  value,
  accent,
}: {
  label: ReactNode;
  value: ReactNode;
  accent: string;
}) {
  return (
    <div className="premium-card" style={{ padding: '20px' }}>
      <div
        style={{
          color: accent,
          fontSize: '0.74rem',
          fontWeight: '800',
          textTransform: 'uppercase',
          letterSpacing: '0.05em',
        }}
      >
        {label}
      </div>
      <div
        className="table-nums"
        style={{ fontSize: '1.8rem', fontWeight: '950', marginTop: '10px', color: '#fff' }}
      >
        {value}
      </div>
    </div>
  );
}
