'use client';

import { useMemo, useState, type ReactNode } from 'react';
import { ArrowLeftRight, Landmark, Plus, Receipt, Trash2, TrendingUp } from 'lucide-react';
import { useNotifications } from '@/app/components/NotificationContext';
import { MoneyValue } from '@/app/components/ui/MoneyValue';
import { PageState } from '@/app/components/ui/PageState';
import { formatDate, formatDateTime } from '@/lib/utils/format';
import type { Account, SemanticTransactionType, Stock, Transaction } from '@/lib/types';

const initialAccounts: Account[] = [
  {
    id: 1,
    name: 'Primary Bank',
    bankName: 'Primary Bank',
    type: 'Savings',
    balance: 150000,
    currency: 'INR',
  },
  {
    id: 2,
    name: 'Broker Wallet',
    bankName: 'FIN Broker',
    type: 'Investment',
    balance: 25000,
    currency: 'INR',
  },
];

const semanticLabels: Record<SemanticTransactionType, string> = {
  INCOME: 'Income',
  EXPENSE: 'Expense',
  TRANSFER: 'Transfer',
  INVESTMENT_BUY: 'Investment Buy',
  INVESTMENT_SELL: 'Investment Sell',
  ADJUSTMENT: 'Adjustment',
};

export default function QASmokePage() {
  const { showNotification, showActionNotification } = useNotifications();

  const [accounts, setAccounts] = useState<Account[]>(initialAccounts);
  const [stocks, setStocks] = useState<Stock[]>([]);
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [pendingDeleteIds, setPendingDeleteIds] = useState<number[]>([]);
  const [updatedAt, setUpdatedAt] = useState(new Date().toISOString());
  const [nextId, setNextId] = useState(1);

  const [stockSymbol, setStockSymbol] = useState('INFY');
  const [stockName, setStockName] = useState('Infosys Ltd');
  const [stockQuantity, setStockQuantity] = useState('10');
  const [stockPrice, setStockPrice] = useState('1500');
  const [stockAccountId, setStockAccountId] = useState('1');

  const [expenseDescription, setExpenseDescription] = useState('Groceries');
  const [expenseCategory, setExpenseCategory] = useState('Food');
  const [expenseAmount, setExpenseAmount] = useState('1800');
  const [expenseAccountId, setExpenseAccountId] = useState('1');

  const [transferAmount, setTransferAmount] = useState('5000');
  const [transferFromId, setTransferFromId] = useState('1');
  const [transferToId, setTransferToId] = useState('2');

  const visibleTransactions = useMemo(
    () => transactions.filter((transaction) => !pendingDeleteIds.includes(transaction.id)),
    [pendingDeleteIds, transactions]
  );

  const expenseItems = useMemo(
    () =>
      visibleTransactions
        .filter((transaction) => transaction.transactionType === 'EXPENSE')
        .sort((a, b) => b.date.localeCompare(a.date)),
    [visibleTransactions]
  );

  const sortedHoldings = useMemo(
    () => [...stocks].sort((a, b) => b.currentValue - a.currentValue),
    [stocks]
  );

  const pushTransaction = (transaction: Omit<Transaction, 'id'>) => {
    setTransactions((current) => [{ id: nextId, ...transaction }, ...current]);
    setNextId((current) => current + 1);
    setUpdatedAt(new Date().toISOString());
  };

  const adjustAccountBalance = (accountId: number, delta: number) => {
    setAccounts((current) =>
      current.map((account) =>
        account.id === accountId ? { ...account, balance: account.balance + delta } : account
      )
    );
  };

  const handleAddStock = (event: React.FormEvent) => {
    event.preventDefault();

    const quantity = Number(stockQuantity);
    const price = Number(stockPrice);
    const accountId = Number(stockAccountId);
    const amount = quantity * price;

    const stock: Stock = {
      id: nextId,
      symbol: stockSymbol.trim().toUpperCase(),
      companyName: stockName.trim(),
      quantity,
      avgPrice: price,
      currentPrice: price,
      previousPrice: price,
      exchange: 'NSE',
      investmentAmount: amount,
      currentValue: amount,
      pnl: 0,
      pnlPercentage: 0,
    };

    setStocks((current) => [stock, ...current]);
    adjustAccountBalance(accountId, -amount);
    pushTransaction({
      date: new Date().toISOString().split('T')[0],
      description: `BUY Stock: ${stock.symbol}`,
      category: 'Investment',
      type: 'Expense',
      transactionType: 'INVESTMENT_BUY',
      amount,
      accountId,
      metadata: { autoGenerated: true, sourceTable: 'stocks' },
    });
    showNotification('success', `${stock.symbol} added to holdings and ledger`);
  };

  const handleAddExpense = (event: React.FormEvent) => {
    event.preventDefault();

    const amount = Number(expenseAmount);
    const accountId = Number(expenseAccountId);

    adjustAccountBalance(accountId, -amount);
    pushTransaction({
      date: new Date().toISOString().split('T')[0],
      description: expenseDescription.trim(),
      category: expenseCategory.trim(),
      type: 'Expense',
      transactionType: 'EXPENSE',
      amount,
      accountId,
      metadata: {},
    });
    showNotification('success', 'Expense added to Expenses and Ledger');
  };

  const handleTransfer = (event: React.FormEvent) => {
    event.preventDefault();

    const amount = Number(transferAmount);
    const sourceId = Number(transferFromId);
    const targetId = Number(transferToId);

    if (sourceId === targetId) {
      showNotification('error', 'Choose different source and destination accounts.');
      return;
    }

    const targetAccount = accounts.find((account) => account.id === targetId);

    adjustAccountBalance(sourceId, -amount);
    adjustAccountBalance(targetId, amount);
    pushTransaction({
      date: new Date().toISOString().split('T')[0],
      description: `Transfer to ${targetAccount?.name ?? 'account'}`,
      category: 'Transfer',
      type: 'Expense',
      transactionType: 'TRANSFER',
      amount,
      accountId: sourceId,
      metadata: {
        targetAccountId: targetId,
        targetAccountName: targetAccount?.name,
      },
    });
    showNotification('success', 'Transfer added to Ledger and balances updated');
  };

  const requestDelete = (transaction: Transaction) => {
    setPendingDeleteIds((current) => [...current, transaction.id]);
    showActionNotification({
      type: 'warning',
      message: `${transaction.description} removed from view. Undo within 8 seconds to restore it.`,
      actionLabel: 'Undo',
      duration: 8000,
      onAction: () => {
        setPendingDeleteIds((current) => current.filter((id) => id !== transaction.id));
        showNotification('info', 'Transaction restored');
      },
      onDismiss: () => {
        setTransactions((current) => current.filter((item) => item.id !== transaction.id));
        setPendingDeleteIds((current) => current.filter((id) => id !== transaction.id));
        setUpdatedAt(new Date().toISOString());
        showNotification('success', 'Transaction deleted');
      },
    });
  };

  return (
    <div className="page-container">
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          gap: '16px',
          alignItems: 'flex-start',
          marginBottom: '24px',
          flexWrap: 'wrap',
        }}
      >
        <div>
          <h1 className="page-title" style={{ margin: 0 }}>
            QA Smoke Harness
          </h1>
          <p className="page-subtitle" style={{ marginTop: '8px' }}>
            Browser automation surface for stock buys, expenses, transfers, undo delete, and
            accessibility checks.
          </p>
          <p style={{ margin: '10px 0 0', color: 'var(--muted)', fontSize: '0.82rem' }}>
            As of {formatDateTime(updatedAt)}
          </p>
        </div>
      </div>

      <div className="grid-responsive-4" style={{ gap: '16px', marginBottom: '24px' }}>
        <SmokeStatCard
          icon={<Landmark size={16} />}
          label="Cash Available"
          value={
            <MoneyValue
              amount={accounts.reduce((sum, account) => sum + account.balance, 0)}
              compact={false}
            />
          }
        />
        <SmokeStatCard
          icon={<TrendingUp size={16} />}
          label="Invested"
          value={
            <MoneyValue
              amount={stocks.reduce((sum, stock) => sum + stock.investmentAmount, 0)}
              compact={false}
            />
          }
        />
        <SmokeStatCard
          icon={<Receipt size={16} />}
          label="Expenses"
          value={
            <MoneyValue
              amount={expenseItems.reduce((sum, transaction) => sum + transaction.amount, 0)}
              compact={false}
            />
          }
        />
        <SmokeStatCard
          icon={<ArrowLeftRight size={16} />}
          label="Ledger Entries"
          value={visibleTransactions.length}
        />
      </div>

      <div className="grid-responsive-2" style={{ gap: '16px', marginBottom: '24px' }}>
        <section
          className="premium-card"
          style={{ padding: '20px' }}
          aria-labelledby="qa-stock-form"
        >
          <h2 id="qa-stock-form" style={{ marginTop: 0 }}>
            Add Stock
          </h2>
          <form onSubmit={handleAddStock} style={{ display: 'grid', gap: '12px' }}>
            <label>
              <span className="sr-only">Symbol</span>
              <input
                className="form-input"
                value={stockSymbol}
                onChange={(event) => setStockSymbol(event.target.value)}
                aria-label="Stock symbol"
                placeholder="INFY"
              />
            </label>
            <label>
              <span className="sr-only">Company name</span>
              <input
                className="form-input"
                value={stockName}
                onChange={(event) => setStockName(event.target.value)}
                aria-label="Company name"
                placeholder="Infosys Ltd"
              />
            </label>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '12px' }}>
              <input
                className="form-input table-nums"
                value={stockQuantity}
                onChange={(event) => setStockQuantity(event.target.value)}
                aria-label="Stock quantity"
                type="number"
                min="1"
              />
              <input
                className="form-input table-nums"
                value={stockPrice}
                onChange={(event) => setStockPrice(event.target.value)}
                aria-label="Stock buy price"
                type="number"
                min="1"
              />
              <select
                className="form-input"
                value={stockAccountId}
                onChange={(event) => setStockAccountId(event.target.value)}
                aria-label="Stock source account"
              >
                {accounts.map((account) => (
                  <option key={account.id} value={account.id}>
                    {account.name}
                  </option>
                ))}
              </select>
            </div>
            <button type="submit" className="add-transaction-btn">
              <Plus size={16} />
              Add Stock
            </button>
          </form>
        </section>

        <section
          className="premium-card"
          style={{ padding: '20px' }}
          aria-labelledby="qa-expense-form"
        >
          <h2 id="qa-expense-form" style={{ marginTop: 0 }}>
            Add Expense
          </h2>
          <form onSubmit={handleAddExpense} style={{ display: 'grid', gap: '12px' }}>
            <input
              className="form-input"
              value={expenseDescription}
              onChange={(event) => setExpenseDescription(event.target.value)}
              aria-label="Expense description"
              placeholder="Groceries"
            />
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '12px' }}>
              <input
                className="form-input"
                value={expenseCategory}
                onChange={(event) => setExpenseCategory(event.target.value)}
                aria-label="Expense category"
                placeholder="Food"
              />
              <input
                className="form-input table-nums"
                value={expenseAmount}
                onChange={(event) => setExpenseAmount(event.target.value)}
                aria-label="Expense amount"
                type="number"
                min="1"
              />
              <select
                className="form-input"
                value={expenseAccountId}
                onChange={(event) => setExpenseAccountId(event.target.value)}
                aria-label="Expense account"
              >
                {accounts.map((account) => (
                  <option key={account.id} value={account.id}>
                    {account.name}
                  </option>
                ))}
              </select>
            </div>
            <button type="submit" className="add-transaction-btn">
              <Plus size={16} />
              Add Expense
            </button>
          </form>
        </section>
      </div>

      <section
        className="premium-card"
        style={{ padding: '20px', marginBottom: '24px' }}
        aria-labelledby="qa-transfer-form"
      >
        <h2 id="qa-transfer-form" style={{ marginTop: 0 }}>
          Transfer Between Accounts
        </h2>
        <form
          onSubmit={handleTransfer}
          style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr auto', gap: '12px' }}
        >
          <select
            className="form-input"
            value={transferFromId}
            onChange={(event) => setTransferFromId(event.target.value)}
            aria-label="Transfer from account"
          >
            {accounts.map((account) => (
              <option key={account.id} value={account.id}>
                {account.name}
              </option>
            ))}
          </select>
          <select
            className="form-input"
            value={transferToId}
            onChange={(event) => setTransferToId(event.target.value)}
            aria-label="Transfer to account"
          >
            {accounts.map((account) => (
              <option key={account.id} value={account.id}>
                {account.name}
              </option>
            ))}
          </select>
          <input
            className="form-input table-nums"
            value={transferAmount}
            onChange={(event) => setTransferAmount(event.target.value)}
            aria-label="Transfer amount"
            type="number"
            min="1"
          />
          <button type="submit" className="add-transaction-btn">
            Transfer
          </button>
        </form>
      </section>

      <div className="grid-responsive-2" style={{ gap: '16px', marginBottom: '24px' }}>
        <section className="premium-card" style={{ padding: '20px' }} aria-labelledby="qa-accounts">
          <h2 id="qa-accounts" style={{ marginTop: 0 }}>
            Accounts
          </h2>
          <div style={{ display: 'grid', gap: '12px' }}>
            {accounts.map((account) => (
              <div
                key={account.id}
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  gap: '12px',
                  alignItems: 'center',
                  padding: '14px 16px',
                  borderRadius: '16px',
                  border: '1px solid rgba(255,255,255,0.08)',
                  background: 'rgba(255,255,255,0.03)',
                }}
              >
                <div>
                  <strong>{account.name}</strong>
                  <p style={{ margin: '6px 0 0', color: 'var(--muted)', fontSize: '0.82rem' }}>
                    {account.type}
                  </p>
                </div>
                <div data-testid={`account-balance-${account.id}`} className="table-nums">
                  <MoneyValue amount={account.balance} compact={false} />
                </div>
              </div>
            ))}
          </div>
        </section>

        <section
          className="premium-card"
          style={{ padding: '20px' }}
          aria-labelledby="qa-stock-holdings"
        >
          <h2 id="qa-stock-holdings" style={{ marginTop: 0 }}>
            Stock Holdings
          </h2>
          {sortedHoldings.length === 0 ? (
            <PageState
              title="No stock holdings yet"
              description="Use the Add Stock form to create the first investment buy for smoke testing."
            />
          ) : (
            <div style={{ display: 'grid', gap: '12px' }}>
              {sortedHoldings.map((stock) => (
                <div
                  key={stock.id}
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    gap: '12px',
                    alignItems: 'center',
                    padding: '14px 16px',
                    borderRadius: '16px',
                    border: '1px solid rgba(255,255,255,0.08)',
                    background: 'rgba(255,255,255,0.03)',
                  }}
                >
                  <div>
                    <strong>{stock.symbol}</strong>
                    <p style={{ margin: '6px 0 0', color: 'var(--muted)', fontSize: '0.82rem' }}>
                      {stock.quantity} shares @{' '}
                      <MoneyValue amount={stock.avgPrice} compact={false} />
                    </p>
                  </div>
                  <div className="table-nums">
                    <MoneyValue amount={stock.currentValue} compact={false} />
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>
      </div>

      <div className="grid-responsive-2" style={{ gap: '16px' }}>
        <section className="premium-card" style={{ padding: '20px' }} aria-labelledby="qa-expenses">
          <h2 id="qa-expenses" style={{ marginTop: 0 }}>
            Expenses View
          </h2>
          {expenseItems.length === 0 ? (
            <PageState
              title="No expenses yet"
              description="Use the Add Expense form to verify expense semantics and undo delete."
            />
          ) : (
            <div style={{ display: 'grid', gap: '12px' }}>
              {expenseItems.map((transaction) => (
                <div
                  key={transaction.id}
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    gap: '12px',
                    alignItems: 'center',
                    padding: '14px 16px',
                    borderRadius: '16px',
                    border: '1px solid rgba(255,255,255,0.08)',
                    background: 'rgba(255,255,255,0.03)',
                  }}
                >
                  <div>
                    <strong>{transaction.description}</strong>
                    <p style={{ margin: '6px 0 0', color: 'var(--muted)', fontSize: '0.82rem' }}>
                      {transaction.category} | {formatDate(transaction.date)}
                    </p>
                  </div>
                  <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
                    <div className="table-nums">
                      <MoneyValue amount={transaction.amount} compact={false} />
                    </div>
                    <button
                      type="button"
                      className="action-btn action-btn--delete"
                      data-label="Delete"
                      title="Delete expense"
                      aria-label={`Delete expense ${transaction.description}`}
                      onClick={() => requestDelete(transaction)}
                    >
                      <Trash2 size={16} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>

        <section className="premium-card" style={{ padding: '20px' }} aria-labelledby="qa-ledger">
          <h2 id="qa-ledger" style={{ marginTop: 0 }}>
            Ledger
          </h2>
          {visibleTransactions.length === 0 ? (
            <PageState
              title="No ledger activity yet"
              description="Every stock buy, expense, and transfer added above should appear here."
            />
          ) : (
            <div style={{ display: 'grid', gap: '12px' }}>
              {visibleTransactions.map((transaction) => (
                <div
                  key={transaction.id}
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    gap: '12px',
                    alignItems: 'center',
                    padding: '14px 16px',
                    borderRadius: '16px',
                    border: '1px solid rgba(255,255,255,0.08)',
                    background: 'rgba(255,255,255,0.03)',
                  }}
                >
                  <div>
                    <strong>{transaction.description}</strong>
                    <p style={{ margin: '6px 0 0', color: 'var(--muted)', fontSize: '0.82rem' }}>
                      <span
                        style={{
                          display: 'inline-flex',
                          borderRadius: '999px',
                          padding: '3px 8px',
                          marginRight: '8px',
                          background: 'rgba(106,166,255,0.12)',
                          color: '#6aa6ff',
                        }}
                      >
                        {semanticLabels[transaction.transactionType]}
                      </span>
                      {formatDate(transaction.date)}
                    </p>
                  </div>
                  <div className="table-nums" data-testid={`ledger-entry-${transaction.id}`}>
                    <MoneyValue amount={transaction.amount} compact={false} />
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>
      </div>
    </div>
  );
}

function SmokeStatCard({
  icon,
  label,
  value,
}: {
  icon: ReactNode;
  label: string;
  value: ReactNode;
}) {
  return (
    <div className="premium-card" style={{ padding: '20px' }}>
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          color: '#6aa6ff',
          marginBottom: '10px',
        }}
      >
        {icon}
        <span style={{ fontSize: '0.76rem', fontWeight: 800, textTransform: 'uppercase' }}>
          {label}
        </span>
      </div>
      <div style={{ fontSize: '1.35rem', fontWeight: 900 }}>{value}</div>
    </div>
  );
}
