import type { Transaction } from '@/lib/types';
import {
  getTransactionSignedAmount,
  inferDirectionFromSemanticType,
  isAutoGeneratedTransaction,
  isExpenseTransaction,
  isIncomeTransaction,
  isInvestmentActivity,
  isTransferTransaction,
  normalizeTransactionType,
} from '@/lib/utils/transactions';

const baseTransaction: Transaction = {
  id: 1,
  date: '2026-03-24',
  description: 'Test transaction',
  category: 'Other',
  type: 'Expense',
  transactionType: 'EXPENSE',
  amount: 1500,
  accountId: 1,
  createdAt: '2026-03-24T12:00:00.000Z',
  updatedAt: '2026-03-24T12:00:00.000Z',
  metadata: {},
};

describe('normalizeTransactionType', () => {
  it('preserves explicit semantic types', () => {
    expect(normalizeTransactionType('TRANSFER')).toBe('TRANSFER');
  });

  it('maps legacy investment-like records to investment buy', () => {
    expect(normalizeTransactionType(undefined, 'Expense', 'BUY Stock: INFY', 'Investments')).toBe(
      'INVESTMENT_BUY'
    );
  });

  it('maps transfer-like records to transfer', () => {
    expect(normalizeTransactionType(undefined, 'Expense', 'Transfer to Broker', 'Transfer')).toBe(
      'TRANSFER'
    );
  });

  it('falls back to direction-based income/expense types', () => {
    expect(normalizeTransactionType(undefined, 'Income', 'Salary credit', 'Salary')).toBe('INCOME');
    expect(normalizeTransactionType(undefined, 'Expense', 'Groceries', 'Food')).toBe('EXPENSE');
  });
});

describe('transaction helpers', () => {
  it('infers direction from semantic type', () => {
    expect(inferDirectionFromSemanticType('INCOME')).toBe('Income');
    expect(inferDirectionFromSemanticType('INVESTMENT_SELL')).toBe('Income');
    expect(inferDirectionFromSemanticType('TRANSFER')).toBe('Expense');
  });

  it('classifies transaction categories correctly', () => {
    expect(isExpenseTransaction(baseTransaction)).toBe(true);
    expect(
      isIncomeTransaction({ ...baseTransaction, type: 'Income', transactionType: 'INCOME' })
    ).toBe(true);
    expect(
      isTransferTransaction({
        ...baseTransaction,
        description: 'Broker transfer',
        transactionType: 'TRANSFER',
      })
    ).toBe(true);
    expect(
      isInvestmentActivity({
        ...baseTransaction,
        description: 'BUY Stock: INFY',
        transactionType: 'INVESTMENT_BUY',
      })
    ).toBe(true);
  });

  it('returns signed amounts based on transaction direction', () => {
    expect(getTransactionSignedAmount(baseTransaction)).toBe(-1500);
    expect(
      getTransactionSignedAmount({ ...baseTransaction, type: 'Income', transactionType: 'INCOME' })
    ).toBe(1500);
  });

  it('detects auto-generated transactions from metadata', () => {
    expect(isAutoGeneratedTransaction({ autoGenerated: true })).toBe(true);
    expect(isAutoGeneratedTransaction({ autoGenerated: false })).toBe(false);
    expect(isAutoGeneratedTransaction()).toBe(false);
  });
});
