import type {
  SemanticTransactionType,
  Transaction,
  TransactionDirection,
  TransactionMetadata,
} from '@/lib/types';

export const SEMANTIC_TRANSACTION_LABELS: Record<SemanticTransactionType, string> = {
  INCOME: 'Income',
  EXPENSE: 'Expense',
  TRANSFER: 'Transfer',
  INVESTMENT_BUY: 'Investment Buy',
  INVESTMENT_SELL: 'Investment Sell',
  ADJUSTMENT: 'Adjustment',
};

export function inferDirectionFromSemanticType(
  transactionType: SemanticTransactionType
): TransactionDirection {
  if (transactionType === 'INCOME' || transactionType === 'INVESTMENT_SELL') {
    return 'Income';
  }

  return 'Expense';
}

export function normalizeTransactionType(
  rawType?: string | null,
  fallbackDirection: TransactionDirection = 'Expense',
  description = '',
  category = ''
): SemanticTransactionType {
  const normalized = rawType?.toUpperCase();

  switch (normalized) {
    case 'INCOME':
    case 'EXPENSE':
    case 'TRANSFER':
    case 'INVESTMENT_BUY':
    case 'INVESTMENT_SELL':
    case 'ADJUSTMENT':
      return normalized;
    default:
      break;
  }

  const normalizedCategory = category.toLowerCase();
  const normalizedDescription = description.toLowerCase();

  if (
    normalizedCategory.includes('investment') ||
    normalizedDescription.startsWith('buy ') ||
    normalizedDescription.includes('fno entry')
  ) {
    return 'INVESTMENT_BUY';
  }

  if (
    normalizedDescription.startsWith('sell ') ||
    normalizedDescription.includes('fno exit') ||
    normalizedDescription.includes('maturity')
  ) {
    return 'INVESTMENT_SELL';
  }

  if (
    normalizedCategory.includes('transfer') ||
    normalizedDescription.includes('transfer to') ||
    normalizedDescription.includes('transfer from')
  ) {
    return 'TRANSFER';
  }

  return fallbackDirection === 'Income' ? 'INCOME' : 'EXPENSE';
}

export function isExpenseTransaction(transaction: Transaction): boolean {
  return transaction.transactionType === 'EXPENSE';
}

export function isIncomeTransaction(transaction: Transaction): boolean {
  return transaction.transactionType === 'INCOME';
}

export function isTransferTransaction(transaction: Transaction): boolean {
  return transaction.transactionType === 'TRANSFER';
}

export function isInvestmentActivity(transaction: Transaction): boolean {
  return (
    transaction.transactionType === 'INVESTMENT_BUY' ||
    transaction.transactionType === 'INVESTMENT_SELL'
  );
}

export function getTransactionSemanticLabel(transactionType: SemanticTransactionType): string {
  return SEMANTIC_TRANSACTION_LABELS[transactionType];
}

export function getTransactionSignedAmount(transaction: Transaction): number {
  if (transaction.type === 'Income') {
    return transaction.amount;
  }

  return -transaction.amount;
}

export function getTransferTargetAccountId(metadata?: TransactionMetadata): number | undefined {
  if (!metadata?.targetAccountId) {
    return undefined;
  }

  return Number(metadata.targetAccountId);
}

export function getTransactionSourceLabel(metadata?: TransactionMetadata): string | undefined {
  return metadata?.sourceTable ? String(metadata.sourceTable) : undefined;
}

export function isAutoGeneratedTransaction(metadata?: TransactionMetadata): boolean {
  return metadata?.autoGenerated === true;
}
