'use client';

import { useMemo, useState, type ReactNode } from 'react';
import { Plus, X, Coffee, Edit3, Trash2, Car, Home, Heart, GraduationCap, Zap } from 'lucide-react';
import { useNotifications } from '../components/NotificationContext';
import { useLedger, useSettings } from '../components/FinanceContext';
import { Transaction } from '@/lib/types';
import { isExpenseTransaction } from '@/lib/utils/transactions';
import { formatDate } from '@/lib/utils/format';
import { MoneyValue } from '@/app/components/ui/MoneyValue';
import { PageSkeleton, PageState } from '@/app/components/ui/PageState';

export default function ExpensesClient() {
  const {
    accounts,
    transactions,
    addTransaction,
    updateTransaction,
    deleteTransaction,
    loading,
    error,
    lastUpdatedAt,
  } = useLedger();
  const { settings } = useSettings();
  const { showNotification, showActionNotification } = useNotifications();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editId, setEditId] = useState<number | null>(null);
  const [pendingDeleteIds, setPendingDeleteIds] = useState<number[]>([]);
  const [selectedAccountId, setSelectedAccountId] = useState<number | ''>(
    settings.defaultSalaryAccountId || ''
  );

  const [amount, setAmount] = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('Food');
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);

  const expenseItems = useMemo(
    () =>
      transactions
        .filter((transaction) => isExpenseTransaction(transaction))
        .filter((transaction) => !pendingDeleteIds.includes(transaction.id))
        .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()),
    [pendingDeleteIds, transactions]
  );

  const categoriesMap = useMemo(
    () =>
      expenseItems.reduce(
        (acc, item) => {
          const nextCategory = item.category || 'Other';
          if (!acc[nextCategory]) acc[nextCategory] = { total: 0, count: 0 };
          acc[nextCategory].total += item.amount;
          acc[nextCategory].count += 1;
          return acc;
        },
        {} as Record<string, { total: number; count: number }>
      ),
    [expenseItems]
  );

  const categories = useMemo(
    () => Object.entries(categoriesMap).sort((a, b) => b[1].total - a[1].total),
    [categoriesMap]
  );

  const totalExpenses = useMemo(
    () => expenseItems.reduce((sum, item) => sum + item.amount, 0),
    [expenseItems]
  );

  const avgMonthlySpending = useMemo(() => {
    if (expenseItems.length === 0) return 0;

    const dates = expenseItems.map((item) => new Date(item.date).getTime());
    const earliest = Math.min(...dates);
    const latest = Math.max(...dates);
    const monthsDiff = Math.max(1, Math.ceil((latest - earliest) / (1000 * 60 * 60 * 24 * 30)));
    return totalExpenses / monthsDiff;
  }, [expenseItems, totalExpenses]);

  const resetForm = () => {
    setAmount('');
    setDescription('');
    setCategory('Food');
    setDate(new Date().toISOString().split('T')[0]);
    setEditId(null);
  };

  const handleLogExpense = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!amount || !description) return;

    const transactionPayload = {
      date,
      description,
      category,
      type: 'Expense' as const,
      transactionType: 'EXPENSE' as const,
      amount: parseFloat(amount),
      accountId: selectedAccountId ? Number(selectedAccountId) : undefined,
      metadata: {
        autoGenerated: false,
        sourceTable: 'transactions',
      },
    };

    if (editId) {
      await updateTransaction(editId, transactionPayload);
      showNotification('success', 'Expense updated');
    } else {
      await addTransaction(transactionPayload);
      showNotification('success', 'Expense saved');
    }

    resetForm();
    setIsModalOpen(false);
  };

  const handleEdit = (item: Transaction) => {
    setEditId(item.id);
    setAmount(item.amount.toString());
    setDescription(item.description);
    setCategory(String(item.category));
    setDate(item.date);
    setSelectedAccountId(item.accountId || '');
    setIsModalOpen(true);
  };

  const scheduleDelete = (item: Transaction) => {
    setPendingDeleteIds((current) => [...current, item.id]);
    showActionNotification({
      type: 'warning',
      message: `${item.description} removed from view. Undo within 8 seconds to restore it.`,
      actionLabel: 'Undo',
      duration: 8000,
      onAction: () => {
        setPendingDeleteIds((current) => current.filter((id) => id !== item.id));
        showNotification('info', 'Expense restored');
      },
      onDismiss: async () => {
        await deleteTransaction(item.id);
        setPendingDeleteIds((current) => current.filter((id) => id !== item.id));
        showNotification('success', 'Expense deleted');
      },
    });
  };

  const getCategoryIcon = (expenseCategory: string) => {
    switch (expenseCategory) {
      case 'Food':
        return <Coffee size={20} />;
      case 'Transport':
        return <Car size={20} />;
      case 'Shopping':
        return <Home size={20} />;
      case 'Healthcare':
        return <Heart size={20} />;
      case 'Education':
        return <GraduationCap size={20} />;
      case 'Utilities':
        return <Zap size={20} />;
      default:
        return <Coffee size={20} />;
    }
  };

  if (loading) {
    return (
      <div className="page-container">
        <PageSkeleton cardCount={3} rowCount={6} />
      </div>
    );
  }

  if (error) {
    return (
      <div className="page-container">
        <PageState
          variant="error"
          title="Expenses could not be loaded"
          description={error}
          actionLabel="Retry"
          onAction={() => window.location.reload()}
        />
      </div>
    );
  }

  return (
    <div className="main-content" style={{ backgroundColor: 'transparent', minHeight: '100vh' }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
        <div className="page-header">
          <div>
            <h1
              className="page-title"
              style={{
                background: 'linear-gradient(to right, #fff, #94a3b8)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
              }}
            >
              Expenses
            </h1>
            <p className="page-subtitle">
              Spending only. Investment buys and transfers are excluded so your budget stays honest.
            </p>
            <p style={{ color: '#64748b', fontSize: '0.82rem', marginTop: '8px' }}>
              As of {lastUpdatedAt ? formatDate(lastUpdatedAt) : 'today'}
            </p>
          </div>
          <button
            onClick={() => setIsModalOpen(true)}
            aria-label="Add expense"
            className="header-add-btn header-add-btn--red"
          >
            <Plus size={18} strokeWidth={3} /> Add Expense
          </button>
        </div>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 250px), 1fr))',
            gap: '24px',
            marginBottom: '32px',
          }}
        >
          <SummaryCard
            label="Total spending"
            value={<MoneyValue amount={totalExpenses} compact={settings.compactNumbers} />}
            sub="Consumption expenses only"
            accent="#ff4d6d"
          />
          <SummaryCard
            label="Average per month"
            value={<MoneyValue amount={avgMonthlySpending} compact={settings.compactNumbers} />}
            sub="Across tracked date range"
            accent="#f59e0b"
          />
          <SummaryCard
            label="Expense categories"
            value={String(categories.length)}
            sub="Active spending buckets"
            accent="#6aa6ff"
          />
        </div>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 420px), 1fr))',
            gap: '32px',
          }}
        >
          <div className="premium-card">
            <h3 style={{ marginBottom: '20px', color: '#fff' }}>Category Breakdown</h3>
            {categories.length > 0 ? (
              <div style={{ display: 'grid', gap: '14px' }}>
                {categories.map(([name, stats]) => (
                  <div key={name} className="tx-row tx-row--expense">
                    <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
                      <div
                        style={{
                          width: '44px',
                          height: '44px',
                          borderRadius: '14px',
                          background: 'rgba(255, 77, 109, 0.12)',
                          color: '#ff4d6d',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                        }}
                      >
                        {getCategoryIcon(name)}
                      </div>
                      <div>
                        <div style={{ color: '#fff', fontWeight: '800' }}>{name}</div>
                        <div style={{ color: '#94a3b8', fontSize: '0.82rem' }}>
                          {stats.count} entries
                        </div>
                      </div>
                    </div>
                    <div className="table-nums" style={{ fontWeight: '900', color: '#ff4d6d' }}>
                      <MoneyValue amount={stats.total} compact={settings.compactNumbers} />
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <PageState
                title="No expenses yet"
                description="Add your first expense to see category trends and monthly spending here."
                actionLabel="Add expense"
                onAction={() => setIsModalOpen(true)}
              />
            )}
          </div>

          <div className="premium-card">
            <h3 style={{ marginBottom: '20px', color: '#fff' }}>Recent Expenses</h3>
            {expenseItems.length > 0 ? (
              <div style={{ display: 'grid', gap: '12px' }}>
                {expenseItems.slice(0, 8).map((item) => (
                  <div key={item.id} className="tx-row tx-row--expense">
                    <div
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '14px',
                        flex: 1,
                        minWidth: 0,
                      }}
                    >
                      <div
                        style={{
                          width: '44px',
                          height: '44px',
                          borderRadius: '14px',
                          background: 'rgba(255, 77, 109, 0.12)',
                          color: '#ff4d6d',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          flexShrink: 0,
                        }}
                      >
                        {getCategoryIcon(String(item.category))}
                      </div>
                      <div style={{ minWidth: 0 }}>
                        <div
                          style={{
                            fontWeight: '800',
                            fontSize: '1rem',
                            color: '#e2e8f0',
                            overflow: 'hidden',
                            textOverflow: 'ellipsis',
                            whiteSpace: 'nowrap',
                          }}
                        >
                          {item.description}
                        </div>
                        <div style={{ fontSize: '0.8rem', color: '#94a3b8', fontWeight: '600' }}>
                          {String(item.category)} | {formatDate(item.date)}
                        </div>
                      </div>
                    </div>

                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                      <div className="table-nums" style={{ color: '#ff4d6d', fontWeight: '950' }}>
                        <MoneyValue amount={item.amount} compact={settings.compactNumbers} />
                      </div>
                      <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                        <button
                          onClick={(event) => {
                            event.stopPropagation();
                            handleEdit(item);
                          }}
                          className="action-btn action-btn--edit"
                          data-label="Edit"
                          title="Edit expense"
                          aria-label="Edit expense"
                        >
                          <Edit3 size={14} />
                        </button>
                        <button
                          onClick={(event) => {
                            event.stopPropagation();
                            scheduleDelete(item);
                          }}
                          className="action-btn action-btn--delete"
                          data-label="Delete"
                          title="Delete expense"
                          aria-label="Delete expense"
                        >
                          <Trash2 size={14} />
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <PageState
                title="No expense history found"
                description="Expenses appear here after you record them. Investment buys are intentionally kept out of this list."
                actionLabel="Add expense"
                onAction={() => setIsModalOpen(true)}
              />
            )}
          </div>
        </div>
      </div>

      {isModalOpen ? (
        <div className="modal-overlay">
          <div className="modal-card" style={{ maxWidth: '480px' }}>
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: '24px',
                gap: '12px',
              }}
            >
              <h2
                style={{
                  fontSize: 'clamp(1.3rem, 3vw, 1.8rem)',
                  fontWeight: '900',
                  margin: 0,
                  color: '#fff',
                }}
              >
                {editId ? 'Edit expense' : 'Add expense'}
              </h2>
              <button
                onClick={() => {
                  setIsModalOpen(false);
                  resetForm();
                }}
                aria-label="Close modal"
                className="modal-close"
                style={{ flexShrink: 0 }}
              >
                <X size={20} />
              </button>
            </div>

            <form
              onSubmit={handleLogExpense}
              aria-label="Expense form"
              style={{ display: 'grid', gap: '20px' }}
            >
              <div>
                <label className="form-label">What did you spend on?</label>
                <input
                  value={description}
                  onChange={(event) => setDescription(event.target.value)}
                  placeholder="e.g. Groceries, taxi, subscription"
                  required
                  className="form-input"
                  autoFocus
                />
              </div>

              <div
                style={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
                  gap: '16px',
                }}
              >
                <div>
                  <label className="form-label">Amount</label>
                  <input
                    type="number"
                    value={amount}
                    onChange={(event) => setAmount(event.target.value)}
                    placeholder="0.00"
                    required
                    className="form-input table-nums"
                  />
                </div>
                <div>
                  <label className="form-label">Date</label>
                  <input
                    type="date"
                    value={date}
                    onChange={(event) => setDate(event.target.value)}
                    className="form-input"
                  />
                </div>
              </div>

              <div>
                <label className="form-label">Category</label>
                <select
                  value={category}
                  onChange={(event) => setCategory(event.target.value)}
                  className="form-input"
                >
                  <option value="Food">Food & Dining</option>
                  <option value="Transport">Transport</option>
                  <option value="Shopping">Shopping</option>
                  <option value="Entertainment">Entertainment</option>
                  <option value="Healthcare">Healthcare</option>
                  <option value="Education">Education</option>
                  <option value="Utilities">Utilities</option>
                  <option value="Other">Other</option>
                </select>
              </div>

              <div>
                <label className="form-label">Account</label>
                <select
                  value={selectedAccountId}
                  onChange={(event) =>
                    setSelectedAccountId(event.target.value ? Number(event.target.value) : '')
                  }
                  className="form-input"
                >
                  <option value="">Log only, do not deduct from an account</option>
                  {accounts.map((account) => (
                    <option key={account.id} value={account.id}>
                      {account.name}
                    </option>
                  ))}
                </select>
              </div>

              <button type="submit" className="btn-primary btn-primary--red">
                {editId ? 'Update Expense' : 'Track Expense'}
              </button>
            </form>
          </div>
        </div>
      ) : null}
    </div>
  );
}

function SummaryCard({
  label,
  value,
  sub,
  accent,
}: {
  label: string;
  value: ReactNode;
  sub: string;
  accent: string;
}) {
  return (
    <div className="premium-card" style={{ padding: '22px' }}>
      <div
        style={{
          color: accent,
          fontSize: '0.75rem',
          fontWeight: '800',
          textTransform: 'uppercase',
          letterSpacing: '0.05em',
        }}
      >
        {label}
      </div>
      <div
        className="table-nums"
        style={{ color: '#fff', fontSize: '2rem', fontWeight: '950', margin: '10px 0 6px' }}
      >
        {value}
      </div>
      <div style={{ color: '#94a3b8', fontSize: '0.82rem' }}>{sub}</div>
    </div>
  );
}
