-- Transaction taxonomy, compact-number preferences, and transfer-aware ledger balance logic

ALTER TABLE public.transactions
ADD COLUMN IF NOT EXISTS transaction_type TEXT;

ALTER TABLE public.app_settings
ADD COLUMN IF NOT EXISTS compact_numbers BOOLEAN DEFAULT FALSE;

UPDATE public.transactions
SET transaction_type = CASE
    WHEN transaction_type IS NOT NULL THEN transaction_type
    WHEN category = 'Transfer' THEN 'TRANSFER'
    WHEN category = 'Forex' AND (description ILIKE 'Forex DEPOSIT%' OR description ILIKE 'Forex WITHDRAWAL%') THEN 'TRANSFER'
    WHEN description ILIKE 'BUY Stock:%' OR description ILIKE 'BUY MF:%' OR description ILIKE 'FnO Entry:%' OR description ILIKE 'BUY Bond:%' THEN 'INVESTMENT_BUY'
    WHEN description ILIKE 'SELL Stock:%' OR description ILIKE 'SELL MF:%' OR description ILIKE 'FnO Exit:%' OR description ILIKE 'SELL Bond:%' OR description ILIKE 'MATURITY Bond:%' THEN 'INVESTMENT_SELL'
    WHEN description ILIKE 'Stock Dividend:%' OR description ILIKE 'MF Dividend:%' THEN 'INCOME'
    WHEN type = 'Income' THEN 'INCOME'
    ELSE 'EXPENSE'
END
WHERE transaction_type IS NULL;

ALTER TABLE public.transactions
ALTER COLUMN transaction_type SET DEFAULT 'EXPENSE';

ALTER TABLE public.transactions
ALTER COLUMN transaction_type SET NOT NULL;

ALTER TABLE public.transactions
DROP CONSTRAINT IF EXISTS transactions_transaction_type_check;

ALTER TABLE public.transactions
ADD CONSTRAINT transactions_transaction_type_check
CHECK (
  transaction_type IN (
    'INCOME',
    'EXPENSE',
    'TRANSFER',
    'INVESTMENT_BUY',
    'INVESTMENT_SELL',
    'ADJUSTMENT'
  )
);

CREATE INDEX IF NOT EXISTS idx_transactions_transaction_type
ON public.transactions(transaction_type);

UPDATE public.transactions
SET metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object(
  'autoGenerated',
  CASE
    WHEN category IN ('Investments', 'Family', 'Forex') THEN TRUE
    WHEN description ILIKE 'BUY %' OR description ILIKE 'SELL %' OR description ILIKE 'FnO %' THEN TRUE
    ELSE COALESCE((metadata ->> 'autoGenerated')::BOOLEAN, FALSE)
  END
)
WHERE metadata IS NULL
   OR NOT (metadata ? 'autoGenerated');

CREATE OR REPLACE FUNCTION public.sync_investment_to_ledger()
RETURNS TRIGGER AS $$
DECLARE
    v_desc TEXT;
    v_type TEXT;
    v_amount DECIMAL(15,2);
    v_symbol TEXT;
    v_date DATE;
    v_transaction_type TEXT;
    v_category TEXT;
    v_metadata JSONB := '{}'::jsonb;
BEGIN
    IF TG_TABLE_NAME IN ('stock_transactions', 'mutual_fund_transactions', 'bond_transactions') THEN
        v_date := NEW.transaction_date;
    ELSIF TG_TABLE_NAME IN ('forex_transactions', 'family_transfers', 'dividends') THEN
        v_date := NEW.date;
    ELSIF TG_TABLE_NAME = 'fno_trades' THEN
        v_date := COALESCE(NEW.exit_date, NEW.entry_date)::DATE;
    ELSE
        v_date := CURRENT_DATE;
    END IF;

    IF TG_TABLE_NAME = 'stock_transactions' THEN
        SELECT symbol INTO v_symbol FROM public.stocks WHERE id = NEW.stock_id;
        v_desc := NEW.transaction_type || ' Stock: ' || COALESCE(v_symbol, 'Unknown') || ' (' || NEW.quantity || ' shares)';
        v_type := CASE WHEN NEW.transaction_type = 'BUY' THEN 'Expense' ELSE 'Income' END;
        v_transaction_type := CASE WHEN NEW.transaction_type = 'BUY' THEN 'INVESTMENT_BUY' ELSE 'INVESTMENT_SELL' END;
        v_category := 'Investments';
        v_amount := CASE
            WHEN NEW.transaction_type = 'BUY'
              THEN NEW.total_amount + COALESCE(NEW.brokerage, 0) + COALESCE(NEW.taxes, 0)
            ELSE NEW.total_amount - (COALESCE(NEW.brokerage, 0) + COALESCE(NEW.taxes, 0))
        END;
        v_metadata := jsonb_build_object(
          'autoGenerated', TRUE,
          'sourceTable', 'stock_transactions',
          'sourceTransactionType', NEW.transaction_type,
          'assetSymbol', COALESCE(v_symbol, 'Unknown')
        );

    ELSIF TG_TABLE_NAME = 'mutual_fund_transactions' THEN
        SELECT name INTO v_symbol FROM public.mutual_funds WHERE id = NEW.mutual_fund_id;
        v_desc := NEW.transaction_type || ' MF: ' || COALESCE(v_symbol, 'Unknown') || ' (' || NEW.units || ' units)';
        v_type := CASE WHEN NEW.transaction_type IN ('BUY', 'SIP') THEN 'Expense' ELSE 'Income' END;
        v_transaction_type := CASE WHEN NEW.transaction_type IN ('BUY', 'SIP') THEN 'INVESTMENT_BUY' ELSE 'INVESTMENT_SELL' END;
        v_category := 'Investments';
        v_amount := NEW.total_amount;
        v_metadata := jsonb_build_object(
          'autoGenerated', TRUE,
          'sourceTable', 'mutual_fund_transactions',
          'sourceTransactionType', NEW.transaction_type,
          'assetSymbol', COALESCE(v_symbol, 'Unknown')
        );

    ELSIF TG_TABLE_NAME = 'fno_trades' THEN
        IF (TG_OP = 'INSERT' AND NEW.status = 'OPEN') THEN
            v_desc := 'FnO Entry: ' || NEW.instrument;
            v_type := 'Expense';
            v_transaction_type := 'INVESTMENT_BUY';
            v_category := 'Investments';
            v_amount := NEW.avg_price * NEW.quantity;
            v_metadata := jsonb_build_object(
              'autoGenerated', TRUE,
              'sourceTable', 'fno_trades',
              'sourceTransactionType', 'OPEN',
              'assetSymbol', NEW.instrument
            );
        ELSIF (TG_OP = 'INSERT' AND NEW.status = 'CLOSED') THEN
            INSERT INTO public.transactions (
              user_id,
              account_id,
              date,
              description,
              category,
              type,
              transaction_type,
              amount,
              metadata
            )
            VALUES (
              NEW.user_id,
              NEW.account_id,
              NEW.entry_date::DATE,
              'FnO Entry: ' || NEW.instrument,
              'Investments',
              'Expense',
              'INVESTMENT_BUY',
              NEW.avg_price * NEW.quantity,
              jsonb_build_object(
                'autoGenerated', TRUE,
                'sourceTable', 'fno_trades',
                'sourceTransactionType', 'OPEN',
                'assetSymbol', NEW.instrument
              )
            );
            v_desc := 'FnO Exit: ' || NEW.instrument;
            v_type := 'Income';
            v_transaction_type := 'INVESTMENT_SELL';
            v_category := 'Investments';
            v_amount := (NEW.avg_price * NEW.quantity) + COALESCE(NEW.pnl, 0);
            v_metadata := jsonb_build_object(
              'autoGenerated', TRUE,
              'sourceTable', 'fno_trades',
              'sourceTransactionType', 'CLOSED',
              'assetSymbol', NEW.instrument
            );
        ELSIF (TG_OP = 'UPDATE' AND OLD.status = 'OPEN' AND NEW.status = 'CLOSED') THEN
            v_desc := 'FnO Exit: ' || NEW.instrument;
            v_type := 'Income';
            v_transaction_type := 'INVESTMENT_SELL';
            v_category := 'Investments';
            v_amount := (NEW.avg_price * NEW.quantity) + COALESCE(NEW.pnl, 0);
            v_metadata := jsonb_build_object(
              'autoGenerated', TRUE,
              'sourceTable', 'fno_trades',
              'sourceTransactionType', 'CLOSED',
              'assetSymbol', NEW.instrument
            );
        ELSE
            RETURN NEW;
        END IF;

    ELSIF TG_TABLE_NAME = 'bond_transactions' THEN
        SELECT name INTO v_symbol FROM public.bonds WHERE id = NEW.bond_id;
        v_desc := NEW.transaction_type || ' Bond: ' || COALESCE(v_symbol, 'Unknown');
        v_type := CASE WHEN NEW.transaction_type = 'BUY' THEN 'Expense' ELSE 'Income' END;
        v_transaction_type := CASE
            WHEN NEW.transaction_type = 'BUY' THEN 'INVESTMENT_BUY'
            WHEN NEW.transaction_type = 'INTEREST' THEN 'INCOME'
            ELSE 'INVESTMENT_SELL'
        END;
        v_category := 'Investments';
        v_amount := NEW.total_amount;
        v_metadata := jsonb_build_object(
          'autoGenerated', TRUE,
          'sourceTable', 'bond_transactions',
          'sourceTransactionType', NEW.transaction_type,
          'assetSymbol', COALESCE(v_symbol, 'Unknown')
        );

    ELSIF TG_TABLE_NAME = 'forex_transactions' THEN
        v_desc := 'Forex ' || NEW.transaction_type || (CASE WHEN NEW.notes IS NOT NULL THEN ': ' || NEW.notes ELSE '' END);
        v_type := CASE WHEN NEW.transaction_type IN ('DEPOSIT', 'LOSS') THEN 'Expense' ELSE 'Income' END;
        v_transaction_type := CASE
            WHEN NEW.transaction_type IN ('DEPOSIT', 'WITHDRAWAL') THEN 'TRANSFER'
            WHEN NEW.transaction_type = 'PROFIT' THEN 'INCOME'
            ELSE 'EXPENSE'
        END;
        v_category := 'Forex';
        v_amount := NEW.amount;
        v_metadata := jsonb_build_object(
          'autoGenerated', TRUE,
          'sourceTable', 'forex_transactions',
          'sourceTransactionType', NEW.transaction_type
        );

    ELSIF TG_TABLE_NAME = 'family_transfers' THEN
        v_desc := 'Family Transfer: ' || NEW.recipient || ' (' || NEW.relationship || ')';
        v_type := 'Expense';
        v_transaction_type := 'EXPENSE';
        v_category := 'Family';
        v_amount := NEW.amount;
        v_metadata := jsonb_build_object(
          'autoGenerated', TRUE,
          'sourceTable', 'family_transfers'
        );

    ELSIF TG_TABLE_NAME = 'dividends' THEN
        IF NEW.stock_id IS NOT NULL THEN
            SELECT symbol INTO v_symbol FROM public.stocks WHERE id = NEW.stock_id;
            v_desc := 'Stock Dividend: ' || v_symbol;
        ELSIF NEW.mf_id IS NOT NULL THEN
            SELECT name INTO v_symbol FROM public.mutual_funds WHERE id = NEW.mf_id;
            v_desc := 'MF Dividend: ' || v_symbol;
        ELSE
            v_desc := 'Dividend Payment';
        END IF;
        v_type := 'Income';
        v_transaction_type := 'INCOME';
        v_category := 'Investment';
        v_amount := NEW.amount;
        v_metadata := jsonb_build_object(
          'autoGenerated', TRUE,
          'sourceTable', 'dividends',
          'assetSymbol', COALESCE(v_symbol, 'Dividend')
        );
    END IF;

    INSERT INTO public.transactions (
      user_id,
      account_id,
      date,
      description,
      category,
      type,
      transaction_type,
      amount,
      metadata
    )
    VALUES (
      NEW.user_id,
      NEW.account_id,
      COALESCE(v_date, CURRENT_DATE),
      v_desc,
      v_category,
      v_type,
      v_transaction_type,
      v_amount,
      v_metadata
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.update_account_balance_on_transaction()
RETURNS TRIGGER AS $$
DECLARE
    v_old_target BIGINT;
    v_new_target BIGINT;
    v_old_delta DECIMAL(15,2);
    v_new_delta DECIMAL(15,2);
BEGIN
    v_old_target := CASE
      WHEN TG_OP IN ('UPDATE', 'DELETE') AND OLD.metadata ? 'targetAccountId'
        THEN (OLD.metadata ->> 'targetAccountId')::BIGINT
      ELSE NULL
    END;

    v_new_target := CASE
      WHEN TG_OP IN ('INSERT', 'UPDATE') AND NEW.metadata ? 'targetAccountId'
        THEN (NEW.metadata ->> 'targetAccountId')::BIGINT
      ELSE NULL
    END;

    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        IF OLD.transaction_type = 'TRANSFER' AND OLD.account_id IS NOT NULL AND v_old_target IS NOT NULL THEN
            UPDATE public.accounts SET balance = balance + OLD.amount WHERE id = OLD.account_id;
            UPDATE public.accounts SET balance = balance - OLD.amount WHERE id = v_old_target;
        ELSIF OLD.account_id IS NOT NULL THEN
            v_old_delta := CASE WHEN OLD.type = 'Income' THEN -OLD.amount ELSE OLD.amount END;
            UPDATE public.accounts SET balance = balance + v_old_delta WHERE id = OLD.account_id;
        END IF;
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        IF NEW.transaction_type = 'TRANSFER' AND NEW.account_id IS NOT NULL AND v_new_target IS NOT NULL THEN
            UPDATE public.accounts SET balance = balance - NEW.amount WHERE id = NEW.account_id;
            UPDATE public.accounts SET balance = balance + NEW.amount WHERE id = v_new_target;
        ELSIF NEW.account_id IS NOT NULL THEN
            v_new_delta := CASE WHEN NEW.type = 'Income' THEN NEW.amount ELSE -NEW.amount END;
            UPDATE public.accounts SET balance = balance + v_new_delta WHERE id = NEW.account_id;
        END IF;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
