'use client';

import { useMemo, useState, type ReactNode } from 'react';
import {
  Plus,
  X,
  Briefcase,
  DollarSign,
  Edit3,
  Trash2,
  BarChart3,
  HandCoins,
  Gem,
  LineChart,
  Home,
  Waves,
} from 'lucide-react';
import { useNotifications } from '../components/NotificationContext';
import { useLedger, useSettings } from '../components/FinanceContext';
import { Transaction, TransactionCategory } from '@/lib/types';
import { isIncomeTransaction } from '@/lib/utils/transactions';
import { formatDate } from '@/lib/utils/format';
import { MoneyValue } from '@/app/components/ui/MoneyValue';
import { PageSkeleton, PageState } from '@/app/components/ui/PageState';

const categoryConfig: Record<string, { icon: ReactNode; color: string; label: string }> = {
  Salary: { icon: <Briefcase size={18} />, color: '#10b981', label: 'Salary' },
  Business: { icon: <HandCoins size={18} />, color: '#6366f1', label: 'Business' },
  Investment: { icon: <LineChart size={18} />, color: '#f59e0b', label: 'Investment' },
  Dividend: { icon: <Gem size={18} />, color: '#ec4899', label: 'Dividend' },
  Rent: { icon: <Home size={18} />, color: '#8b5cf6', label: 'Rent' },
  Bonus: { icon: <Waves size={18} />, color: '#06b6d4', label: 'Bonus' },
  Other: { icon: <DollarSign size={18} />, color: '#94a3b8', label: 'Other' },
};

export default function IncomeClient() {
  const {
    accounts,
    transactions,
    addTransaction,
    updateTransaction,
    deleteTransaction,
    loading,
    error,
    lastUpdatedAt,
  } = useLedger();
  const { settings } = useSettings();
  const { showNotification, showActionNotification } = useNotifications();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editId, setEditId] = useState<number | null>(null);
  const [pendingDeleteIds, setPendingDeleteIds] = useState<number[]>([]);
  const [selectedAccountId, setSelectedAccountId] = useState<number | ''>(
    settings.defaultSalaryAccountId || ''
  );

  const [amount, setAmount] = useState('');
  const [sourceName, setSourceName] = useState('');
  const [category, setCategory] = useState<TransactionCategory>('Salary');
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);

  const incomeItems = useMemo(
    () =>
      transactions
        .filter((transaction) => isIncomeTransaction(transaction))
        .filter((transaction) => !pendingDeleteIds.includes(transaction.id))
        .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()),
    [pendingDeleteIds, transactions]
  );

  const stats = useMemo(() => {
    const total = incomeItems.reduce((sum, item) => sum + item.amount, 0);
    const count = incomeItems.length;
    const average = count > 0 ? total / count : 0;
    const sourcesCount = new Set(incomeItems.map((item) => item.description || 'Unknown')).size;

    return { total, count, average, sourcesCount };
  }, [incomeItems]);

  const categoryData = useMemo(() => {
    const bucket = incomeItems.reduce(
      (acc, item) => {
        const nextCategory = String(item.category) || 'Other';
        if (!acc[nextCategory]) acc[nextCategory] = 0;
        acc[nextCategory] += item.amount;
        return acc;
      },
      {} as Record<string, number>
    );

    return Object.entries(bucket)
      .map(([name, total]) => ({ name, total }))
      .sort((a, b) => b.total - a.total);
  }, [incomeItems]);

  const resetForm = () => {
    setAmount('');
    setSourceName('');
    setCategory('Salary');
    setDate(new Date().toISOString().split('T')[0]);
    setEditId(null);
  };

  const handleLogIncome = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!amount || !sourceName) return;

    const transactionPayload = {
      date,
      description: sourceName,
      category,
      type: 'Income' as const,
      transactionType: 'INCOME' as const,
      amount: parseFloat(amount),
      accountId: selectedAccountId ? Number(selectedAccountId) : undefined,
      metadata: {
        autoGenerated: false,
        sourceTable: 'transactions',
      },
    };

    if (editId) {
      await updateTransaction(editId, transactionPayload);
      showNotification('success', 'Income updated');
    } else {
      await addTransaction(transactionPayload);
      showNotification('success', 'Income saved');
    }

    resetForm();
    setIsModalOpen(false);
  };

  const handleEdit = (item: Transaction) => {
    setEditId(item.id);
    setAmount(item.amount.toString());
    setSourceName(item.description);
    setCategory(item.category as TransactionCategory);
    setDate(item.date);
    setSelectedAccountId(item.accountId || '');
    setIsModalOpen(true);
  };

  const scheduleDelete = (item: Transaction) => {
    setPendingDeleteIds((current) => [...current, item.id]);
    showActionNotification({
      type: 'warning',
      message: `${item.description} removed from view. Undo within 8 seconds to restore it.`,
      actionLabel: 'Undo',
      duration: 8000,
      onAction: () => {
        setPendingDeleteIds((current) => current.filter((id) => id !== item.id));
        showNotification('info', 'Income restored');
      },
      onDismiss: async () => {
        await deleteTransaction(item.id);
        setPendingDeleteIds((current) => current.filter((id) => id !== item.id));
        showNotification('success', 'Income deleted');
      },
    });
  };

  if (loading) {
    return (
      <div className="page-container">
        <PageSkeleton cardCount={3} rowCount={6} />
      </div>
    );
  }

  if (error) {
    return (
      <div className="page-container">
        <PageState
          variant="error"
          title="Income could not be loaded"
          description={error}
          actionLabel="Retry"
          onAction={() => window.location.reload()}
        />
      </div>
    );
  }

  return (
    <div
      className="main-content"
      style={{ backgroundColor: 'transparent', minHeight: '100vh', paddingBottom: '100px' }}
    >
      <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '0 20px' }}>
        <div className="page-header" style={{ marginBottom: '32px' }}>
          <div>
            <h1
              className="page-title"
              style={{
                background: 'linear-gradient(135deg, #10b981 0%, #34d399 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
              }}
            >
              Income Tracker
            </h1>
            <p className="page-subtitle">
              Only true income lives here. Investment sells remain investment activity, not
              earnings.
            </p>
            <p style={{ color: '#64748b', fontSize: '0.82rem', marginTop: '8px' }}>
              As of {lastUpdatedAt ? formatDate(lastUpdatedAt) : 'today'}
            </p>
          </div>
          <button
            onClick={() => setIsModalOpen(true)}
            className="header-add-btn header-add-btn--green"
          >
            <Plus size={20} strokeWidth={3} /> Add Income
          </button>
        </div>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 320px), 1fr))',
            gap: '20px',
            marginBottom: '32px',
          }}
        >
          <SummaryCard
            label="Total earned"
            value={<MoneyValue amount={stats.total} compact={settings.compactNumbers} />}
            sub="Recognized income only"
            accent="#10b981"
            icon={<DollarSign size={24} />}
          />
          <SummaryCard
            label="Average credit"
            value={<MoneyValue amount={stats.average} compact={settings.compactNumbers} />}
            sub={`From ${stats.count} entries`}
            accent="#6aa6ff"
            icon={<BarChart3 size={24} />}
          />
          <SummaryCard
            label="Income sources"
            value={String(stats.sourcesCount)}
            sub="Distinct payers / sources"
            accent="#f59e0b"
            icon={<Briefcase size={24} />}
          />
        </div>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 500px), 1fr))',
            gap: '32px',
          }}
        >
          <div className="premium-card">
            <h3 style={{ marginBottom: '20px', color: '#fff' }}>Breakdown by Type</h3>
            {categoryData.length > 0 ? (
              <div style={{ display: 'grid', gap: '16px' }}>
                {categoryData.map((bucket) => {
                  const config = categoryConfig[bucket.name] || categoryConfig.Other;
                  const percentage = stats.total > 0 ? (bucket.total / stats.total) * 100 : 0;

                  return (
                    <div
                      key={bucket.name}
                      style={{
                        background: 'rgba(255,255,255,0.02)',
                        padding: '16px',
                        borderRadius: '16px',
                        border: '1px solid rgba(255,255,255,0.05)',
                      }}
                    >
                      <div
                        style={{
                          display: 'flex',
                          justifyContent: 'space-between',
                          alignItems: 'center',
                          marginBottom: '10px',
                        }}
                      >
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                          <div
                            style={{
                              width: '38px',
                              height: '38px',
                              borderRadius: '12px',
                              background: `${config.color}20`,
                              color: config.color,
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center',
                            }}
                          >
                            {config.icon}
                          </div>
                          <div>
                            <div style={{ fontWeight: '800', color: '#fff' }}>{config.label}</div>
                            <div style={{ fontSize: '0.78rem', color: '#94a3b8' }}>
                              {percentage.toFixed(1)}% of total
                            </div>
                          </div>
                        </div>
                        <div
                          className="table-nums"
                          style={{ fontWeight: '900', color: config.color }}
                        >
                          <MoneyValue amount={bucket.total} compact={settings.compactNumbers} />
                        </div>
                      </div>
                      <div
                        style={{
                          width: '100%',
                          height: '6px',
                          background: 'rgba(255,255,255,0.05)',
                          borderRadius: '999px',
                          overflow: 'hidden',
                        }}
                      >
                        <div
                          style={{
                            width: `${percentage}%`,
                            height: '100%',
                            background: config.color,
                            borderRadius: '999px',
                          }}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            ) : (
              <PageState
                title="No income yet"
                description="Add your first income entry to see sources and category trends."
                actionLabel="Add income"
                onAction={() => setIsModalOpen(true)}
              />
            )}
          </div>

          <div className="premium-card">
            <h3 style={{ marginBottom: '20px', color: '#fff' }}>Recent Income</h3>
            {incomeItems.length > 0 ? (
              <div style={{ display: 'grid', gap: '12px' }}>
                {incomeItems.slice(0, 12).map((item) => {
                  const config = categoryConfig[String(item.category)] || categoryConfig.Other;

                  return (
                    <div key={item.id} className="tx-row tx-row--income">
                      <div
                        style={{
                          display: 'flex',
                          alignItems: 'center',
                          gap: '14px',
                          flex: 1,
                          minWidth: 0,
                        }}
                      >
                        <div
                          style={{
                            width: '42px',
                            height: '42px',
                            borderRadius: '12px',
                            background: `${config.color}20`,
                            color: config.color,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            flexShrink: 0,
                          }}
                        >
                          {config.icon}
                        </div>
                        <div style={{ minWidth: 0 }}>
                          <div
                            style={{
                              fontWeight: '700',
                              color: '#fff',
                              fontSize: '0.95rem',
                              overflow: 'hidden',
                              textOverflow: 'ellipsis',
                              whiteSpace: 'nowrap',
                            }}
                          >
                            {item.description}
                          </div>
                          <div style={{ fontSize: '0.75rem', color: '#64748b', fontWeight: '600' }}>
                            {formatDate(item.date)}
                          </div>
                        </div>
                      </div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                        <div className="table-nums" style={{ fontWeight: '900', color: '#10b981' }}>
                          <MoneyValue
                            amount={item.amount}
                            compact={settings.compactNumbers}
                            showSign
                          />
                        </div>
                        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                          <button
                            onClick={() => handleEdit(item)}
                            className="mobile-action-btn mobile-action-btn--edit"
                            data-label="Edit"
                            title="Edit income"
                            aria-label="Edit income"
                          >
                            <Edit3 size={14} />
                          </button>
                          <button
                            onClick={() => scheduleDelete(item)}
                            className="mobile-action-btn mobile-action-btn--delete"
                            data-label="Delete"
                            title="Delete income"
                            aria-label="Delete income"
                          >
                            <Trash2 size={14} />
                          </button>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            ) : (
              <PageState
                title="No income history found"
                description="Income entries appear here after you add salary, freelance payouts, refunds, or other genuine earnings."
                actionLabel="Add income"
                onAction={() => setIsModalOpen(true)}
              />
            )}
          </div>
        </div>
      </div>

      {isModalOpen ? (
        <div className="modal-overlay">
          <div className="modal-card" style={{ maxWidth: '500px' }}>
            <button
              onClick={() => {
                setIsModalOpen(false);
                resetForm();
              }}
              className="modal-close"
            >
              <X size={20} />
            </button>

            <h2 className="modal-title">{editId ? 'Edit income' : 'Add income'}</h2>
            <p className="modal-subtitle">
              {editId
                ? 'Modify your earning details'
                : 'Add salary, freelance payments, dividends, or other recognized income'}
            </p>

            <form
              onSubmit={handleLogIncome}
              style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}
            >
              <div>
                <label className="form-label">Source</label>
                <input
                  value={sourceName}
                  onChange={(event) => setSourceName(event.target.value)}
                  placeholder="e.g. Employer, Client, Rental"
                  required
                  className="form-input form-input--green"
                  autoFocus
                />
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <div>
                  <label className="form-label">Amount</label>
                  <input
                    type="number"
                    value={amount}
                    onChange={(event) => setAmount(event.target.value)}
                    placeholder="0.00"
                    required
                    className="form-input form-input--green"
                  />
                </div>
                <div>
                  <label className="form-label">Category</label>
                  <select
                    value={category}
                    onChange={(event) => setCategory(event.target.value as TransactionCategory)}
                    className="form-input form-input--green"
                    style={{ padding: '16px' }}
                  >
                    {Object.keys(categoryConfig).map((entry) => (
                      <option key={entry} value={entry}>
                        {entry}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                <div>
                  <label className="form-label">Date</label>
                  <input
                    type="date"
                    value={date}
                    onChange={(event) => setDate(event.target.value)}
                    className="form-input form-input--green"
                  />
                </div>
                <div>
                  <label className="form-label">Credit account</label>
                  <select
                    value={selectedAccountId}
                    onChange={(event) =>
                      setSelectedAccountId(event.target.value ? Number(event.target.value) : '')
                    }
                    className="form-input form-input--green"
                  >
                    <option value="">No account link</option>
                    {accounts.map((account) => (
                      <option key={account.id} value={account.id}>
                        {account.name}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              <button
                type="submit"
                className="btn-primary btn-primary--green"
                style={{ marginTop: '10px' }}
              >
                {editId ? 'Update Income' : 'Save Income'}
              </button>
            </form>
          </div>
        </div>
      ) : null}
    </div>
  );
}

function SummaryCard({
  label,
  value,
  sub,
  accent,
  icon,
}: {
  label: string;
  value: ReactNode;
  sub: string;
  accent: string;
  icon: ReactNode;
}) {
  return (
    <div className="premium-card" style={{ padding: '22px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '10px', color: accent }}>
        {icon}
        <span
          style={{
            fontSize: '0.75rem',
            fontWeight: '800',
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
          }}
        >
          {label}
        </span>
      </div>
      <div
        className="table-nums"
        style={{ fontSize: '2rem', fontWeight: '950', margin: '10px 0 6px', color: '#fff' }}
      >
        {value}
      </div>
      <div style={{ color: '#94a3b8', fontSize: '0.82rem' }}>{sub}</div>
    </div>
  );
}
